#!/bin/sh
old=$HOME/tcl/Tix4.0b4/src
new=$HOME/tcl/Tix4.0/src 
rm -f Fixup 
files=`(cd ../pTk/mTk; ls tix*.c)`
for f in $files
 do 
  if [ -f $old/$f ]
   then 
    cp ../pTk/mTk/$f .
    if [ -f $new/$f ]
     then 
      if merge $f $old/$f $new/$f 
       then echo "    $f is okay"
       else 
        echo ">>> $f needs fixing"
        echo $f >> Fixup 
      fi 
     else
      echo "No $new/$f";
    fi 
  fi 
 done
old=$HOME/tcl/Tix4.0b4/include
new=$HOME/tcl/Tix4.0/include
files=`(cd ../pTk/mTk; ls tix*.h)`
for f in $files
 do 
  if [ -f $old/$f ]
   then 
    cp ../pTk/mTk/$f .
    if [ -f $new/$f ]
     then 
      if merge $f $old/$f $new/$f 
       then echo "    $f is okay"
       else 
        echo ">>> $f needs fixing"
        echo $f >> Fixup 
      fi 
     else
      echo "No $new/$f";
    fi 
  fi 
 done

