#!/bin/sh 
old=$HOME/tcl/tk4.0
new=$HOME/tcl/tk4.0p1
files=`(cd ../pTk/mTk; ls *.[ch])`
rm -f Fixup 
for f in $files
 do 
  if [ -f $old/$f ]
   then 
    cp ../pTk/mTk/$f .
    if merge $f $old/$f $new/$f 
     then echo "    $f is okay"
     else 
      echo ">>> $f needs fixing"
      echo $f >> Fixup 
    fi 
  fi 
 done
