branches:
  except:
    - /travis/
    - /github-actions/
    - /doozer/
skip_tags: true
shallow_clone: true

environment:
  matrix:
    - perl: strawberryperl
      strawberry_version: 5.32.1.1
    - perl: strawberryperl
      strawberry_version: latest
matrix:
  fast_finish: false
  allow_failures:
    - perl: strawberryperl
      strawberry_version: latest

install:
  - if %perl%==strawberryperl if     "%strawberry_version%"=="latest" cinst strawberryperl
  - if %perl%==strawberryperl if not "%strawberry_version%"=="latest" cinst strawberryperl --version=%strawberry_version%
  - if %perl%==strawberryperl set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
  - set HARNESS_TIMER=1
  - gmake test
