#!/usr/local/bin/perl -w
use strict;
use Tk;
use Tk::FileSelect;

my $mw = MainWindow->new;

my $fs = $mw->FileSelect;
$fs->wmCapture;
$fs->pack(-in => $mw, -expand => 1, -fill => 'both');
$mw->Button(-text => 'Quit', -command => [destroy => $mw])->pack;
MainLoop;

__END__

