#!/usr/local/bin/perl
BEGIN { unshift(@INC,'blib') }
use Tk;
use Tk::Pretty;

sub lots
{
 &Tk::Pretty::PrintArgs;
 return (0..10);
}

sub one
{
 &Tk::Pretty::PrintArgs;
 return 0;
}

print pretty(Tk::Callback->new(\&lots)->Call('a'..'d')),"\n";
print pretty(Tk::Callback->new([\&lots,'A'..'F'])->Call('a'..'d')),"\n";
print pretty(Tk::Callback->new(\&one)->Call('a'..'d')),"\n";
print pretty(Tk::Callback->new([\&one,'A'..'F'])->Call('a'..'d')),"\n";

