#!/usr/local/bin/perl -w



use Tk;

{ 
 my $top = MainWindow->new();
 $top->Button(-text=>"Hello World",-command => sub { exit } )->pack;

 $top->update;

 $top->cget('-gibberish');

}

Tk::MainLoop();

print "Normal Exit\n";
