#! perl
use strict;
my $ext_path = 'Tk';
my $good;
my $file = "auto/$ext_path/.packlist";

for my $dir (@INC) {
  print "Trying $dir/$ext_path/.packlist...\n";
  $good = $dir, last if -f "$dir/$file";
}
die "Cannot find $ext_path/.packlist" unless defined $good;

open L, "$good/$file" or die "open: $!";
my @list = <L>;
close L or die "close: $!";
chomp @list;
chmod 0666, @list or die "chmod list: $!";
unlink @list or die "unlink list: $!";
unlink "$good/$file.old";
rename "$good/$file",  "$good/$file.old" or die "rename: $!";
