#!/usr/local/bin/perl -w
use strict;
use Tk;              
use Data::Dumper;


my $mw = MainWindow->new;
my $b = $mw->Button(-text => 'Quit', -command => [destroy => $mw])->pack;
my $f = $b->cget('-font');               

my @info = $b->fontActual($f);
print Dumper([@info]);
print join(',',$b->fontNames),"\n";
print join(',',$b->fontFamilies),"\n";
print join(',',$b->fontMeasure($f,"Hugo")),"\n";

my $name;
my $size = $f->PostscriptFontName($name); 
print "$name @ $size\n";
my @f = $b->configure('-font');
print Dumper($f,@f);
# MainLoop;

 
