#!/usr/local/bin/perl -w

use Tk;

my $top = MainWindow->new();
$top->wmTracing(1);

my $img = $top->Pixmap('-file' => Tk->findINC("demos/images/QuitPB.xpm"));

# $top->iconify;

$top->Icon('-image' => $img);
$top->iconname("Foo");
$top->title("Mail : Trial");


#$top->after(3000, [ 'Icon', $top, '-background' => 'green' ]);

$top->after(3000, [ iconify => $top ]);
$top->after(6000, [ deiconify => $top ]);

MainLoop();
