#!/usr/local/bin/perl -w

use Tk;

$top = MainWindow->new();

$top->iconify;

$top->Icon('-image' => $top->Pixmap('-file' => Tk->findINC("demos/images/ned.xpm")));

$top->after(3000, [ 'Icon', $top, '-background' => 'green' ]);


$top->iconify;

MainLoop();
