#!/usr/local/bin/perl -w 

chomp($p5 = `pwd`);
@patches = <$p5/patches.001/patch.1[a-z]>;
@patches = grep(!/%$/,@patches);

die "No patches!" unless (@patches);


$dir = 'perl5.001';

sub System
{
 print STDERR join(' ',@_),"\n";
 die "Cannot " . join(' ',@_) if (system(@_));
}

if (-d "$dir.wrk")
 {
  System("rm -rf $dir.wrk"); 
 }
if (-d "$dir")
 {
  print STDERR "Moving $dir to $dir.wrk\n";
  rename("$dir","$dir.wrk") || die "Cannot rename";
 }
System("gtar -xzvf $dir.tar.gz");
chdir($dir) || die "Cannot cd to $dir";
foreach $patch (sort @patches)
 {
  System("sh < $patch");
  System("patch -p1 -N < $patch");
 }
