#!/usr/local/bin/perl -w
use strict;
use Tk;
print "Loading Tk::Pixmap\n";
require Tk::Pixmap;
print "Loaded Tk::Pixmap\n";

my $mw = MainWindow->new;

my $file = Tk->findINC("demos/images/QuitPB.xpm");

die "No file" unless defined($file);

print "Loading $file\n";

my $QuitPB  = $mw->Pixmap('-file' => $file);

print "Pixmap is $QuitPB\n";

my $QuitPBa = $mw->Pixmap('-file' => Tk->findINC("demos/images/QuitPBa.xpm"));


$mw->Button(-image => $QuitPB, -activeimage => $QuitPBa, 
            -background => 'green',
            -activebackground => 'green',
            -command => [destroy => $mw])->pack;
MainLoop;

