#!/usr/local/bin/perl

use lib ("blib",".");

use Tk;

@ARGV = $0 unless (@ARGV);
@data = <>;

$top = MainWindow->new();

$lb  = $top->ScrlListbox(-scrollbars => 'sw',-label => 'sw');
$lb->configure(-labelRelief => 'raised');
$lb->insert('end',@data);
$lb->pack(-side => left, -expand => 1, -fill => 'both'  );

$lb  = $top->ScrlListbox(-scrollbars => 'nw',-label => 'nw');
$lb->configure(-labelRelief => 'raised');
$lb->insert('end',@data);
$lb->pack(-side => left, -expand => 1, -fill => 'both'  );

$lb  = $top->ScrlListbox(-scrollbars => 'se',-label => 'se');
$lb->configure(-labelRelief => 'raised');
$lb->insert('end',@data);
$lb->pack(-side => left, -expand => 1, -fill => 'both'  );

$lb  = $top->ScrlListbox(-scrollbars => 'ne',-label => 'ne');
$lb->configure(-labelRelief => 'raised');
$lb->insert('end',@data);
$lb->pack(-side => left, -expand => 1, -fill => 'both'  );

MainLoop();
