#!/usr/local/bin/perl -w



require Tk;
{
 my $top = MainWindow->new();
 my $w = $top->Button(-text => 'Quit',-command => ['destroy',$top])->pack;
 while (MainWindow->Count)
  {
   Tk->DoOneEvent;
  }
}
print "done:  Enter text:";
print "Text is: ",scalar(<STDIN>),"\n";


