#!/usr/local/bin/perl -w
use strict;

@ARGV = `ls mann/*.n` unless @ARGV;
chomp @ARGV;

my $name;
my $kind;
my $lastSYN = 0;
my $type;
my $Type;
while (<>)
 {
  if ($. == 1)
   {
    my ($leaf) = $ARGV =~ m#/([^/]+)$#;
    my $new    = "man/$leaf";
    close(FILE) if (defined fileno(FILE));
    open(FILE,">$new") || die "Cannot open $new:$!";
    print STDERR "$ARGV -> $new\n";
    ($name = lc($leaf)) =~ s/\..$//;
    ($kind = ucfirst($leaf)) =~ s/\..$//;
   }

  if (/^\\fB$name\s*\\fR\s*\$widget/) # unique for constr in SYNOPSYS
    {
      $_ = "\\fI\$$name\\fR = \\fI\$parent\\fR->\\fB$kind\\fR(\\fR?\\fIoptions\\fR?\\fR);\n"
	 . ".SH \"STANDARD OPTIONS\"\n";
    }
  
  print FILE  $_;
  if (eof)
   {
    close(FILE) if (defined fileno(FILE));
    $. = 0;
    undef $name;
    undef $kind;
   }
 }

