#!/usr/local/bin/perl -w
use strict;

@ARGV = `grep -l WIDGET mann/*.n`; # select Widget man pages

chomp @ARGV;

my $name;
my $kind;
my $lastSHNAME = 0;
my $type;
my $Type;
while (<>)
 {
  if ($. == 1)
   {
    my ($leaf) = $ARGV =~ m#/([^/]+)$#;
    my $new    = "man/$leaf";
    close(FILE) if (defined fileno(FILE));
    open(FILE,">$new") || die "Cannot open $new:$!";
    print STDERR "$ARGV -> $new\n";
    ($name = lc($leaf)) =~ s/\..$//;
    ($kind = ucfirst($leaf)) =~ s/\..$//;
   }

  if ($lastSHNAME && !/Tk::/)
    {
      s/^tix//;
      /^(\w+)/;
      $type = $1;
      $Type = ucfirst($type);
      s/$type/$Type/g;
      $_ = "Tk::" . $_;
    }
  $lastSHNAME= (/^\.SH NAME/ ? 1 : 0);

  s/^\.TH\s+(\w+.*)Tk Generic Methods/".TH Tk::".ucfirst($1)."Tk Widget Classes"/e;
  
  print FILE  $_;
  if (eof)
   {
    close(FILE) if (defined fileno(FILE));
    $. = 0;
    undef $name;
    undef $kind;
   }
 }

