#!/usr/local/bin/perl -w
use strict;

@ARGV = `grep -l WIDGET mann/*.n`; # select Widget man pages

chomp @ARGV;

my $name;
my $kind;

while (<>)
 {
  if ($. == 1)
   {
    my ($leaf) = $ARGV =~ m#/([^/]+)$#;
    my $new    = "man/$leaf";
    close(FILE) if (defined fileno(FILE));
    open(FILE,">$new") || die "Cannot open $new:$!";
    print STDERR "$ARGV -> $new\n";
    ($name = lc($leaf)) =~ s/\..$//;
    ($kind = ucfirst($leaf)) =~ s/\..$//;
   }
  s/^\\fI\$widget->/\\fI\$$name->/;
  s/^\\fI\$widget\\fR->/\\fI\$$name\\fR->/;
  s/he \\fB((?i)$name)\\fR command creates/he \\fB$kind\\fR method creates/;
  s/he \\fBtix((?i)$name)\\fR command creates/he \\fB$kind\\fR method creates/;
  print FILE  $_;
  if (eof)
   {
    close(FILE) if (defined fileno(FILE));
    $. = 0;
    undef $name;
    undef $kind;
   }
 }

