# This Makefile is for the Tk::doc extension to perl.
#
# It was generated automatically by MakeMaker version
# 5.42 (Revision: 1.216) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#	ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker Parameters:

#	NAME => q[Tk::doc]
#	VERSION => q[800.000]
#	XS_VERSION => q[800.000]
#	clean => { FILES=>q[*.htm index.html *.bak] }
#	linkext => { LINKTYPE=>q[] }
#	macro => { TKDIR=>q[..] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/local/lib/perl5/sun4-solaris/5.00404/Config.pm)

# They may have been overridden via Makefile.PL or on the command line
AR = ar
CC = gcc
CCCDLFLAGS = -fPIC
CCDLFLAGS =  
DLEXT = so
DLSRC = dl_dlopen.xs
LD = gcc
LDDLFLAGS = -G -L/usr/local/lib
LDFLAGS =  -L/usr/local/lib
LIBC = /lib/libc.so
LIB_EXT = .a
OBJ_EXT = .o
RANLIB = :
SO = so
EXE_EXT = 


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
NAME = Tk::doc
DISTNAME = Tk-doc
NAME_SYM = Tk_doc
VERSION = 800.000
VERSION_SYM = 800_000
XS_VERSION = 800.000
INST_BIN = .././blib/bin
INST_EXE = .././blib/script
INST_LIB = .././blib/lib
INST_ARCHLIB = .././blib/arch
INST_SCRIPT = .././blib/script
PREFIX = /usr/local
INSTALLDIRS = site
INSTALLPRIVLIB = $(PREFIX)/lib/perl5
INSTALLARCHLIB = $(PREFIX)/lib/perl5/sun4-solaris/5.00404
INSTALLSITELIB = $(PREFIX)/lib/perl5/site_perl
INSTALLSITEARCH = $(PREFIX)/lib/perl5/site_perl/sun4-solaris
INSTALLBIN = $(PREFIX)/bin
INSTALLSCRIPT = $(PREFIX)/bin
PERL_LIB = /usr/local/lib/perl5
PERL_ARCHLIB = /usr/local/lib/perl5/sun4-solaris/5.00404
SITELIBEXP = /usr/local/lib/perl5/site_perl
SITEARCHEXP = /usr/local/lib/perl5/site_perl/sun4-solaris
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/local/lib/perl5/sun4-solaris/5.00404/CORE
PERL = /usr/local/bin/perl
FULLPERL = /usr/local/bin/perl

VERSION_MACRO = VERSION
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"

MAKEMAKER = /usr/local/lib/perl5/ExtUtils/MakeMaker.pm
MM_VERSION = 5.42

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# ROOTEXT = Directory part of FULLEXT with leading slash (eg /DBD)  !!! Deprecated from MM 5.32  !!!
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
FULLEXT = Tk/doc
BASEEXT = doc
PARENT_NAME = Tk::
DLBASE = $(BASEEXT)
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic

# Handy lists of source code files:
XS_FILES= 
C_FILES = 
O_FILES = 
H_FILES = 
MAN1PODS = 
MAN3PODS = 
INST_MAN1DIR = .././blib/man1
INSTALLMAN1DIR = /usr/local/man/man1
MAN1EXT = 1
INST_MAN3DIR = .././blib/man3
INSTALLMAN3DIR = $(PREFIX)/lib/perl5/man/man3
MAN3EXT = 3

# work around a famous dec-osf make(1) feature(?):
makemakerdflt: all

.SUFFIXES:
.SUFFIXES: .xs .c .C .cpp .cxx .cc $(OBJ_EXT)

# Nick wanted to get rid of .PRECIOUS. I don't remember why. I seem to recall, that
# some make implementations will delete the Makefile when we rebuild it. Because
# we call false(1) when we rebuild it. So make(1) is not completely wrong when it
# does so. Our milage may vary.
# .PRECIOUS: Makefile    # seems to be not necessary anymore

.PHONY: all config static dynamic test linkext manifest

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)/Config.pm $(PERL_INC)/config.h

# Where to put things:
INST_LIBDIR      = $(INST_LIB)/Tk
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/Tk

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC  =
INST_DYNAMIC =
INST_BOOT    =

EXPORT_LIST = 

PERL_ARCHIVE = 

TO_INST_PM = 

PM_TO_BLIB = 

GCCOPT =  -Wall -Wno-comment -Wno-unused -D__USE_FIXED_PROTOTYPES__ -MMD -Werror


# --- MakeMaker tool_autosplit section:

# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(PERL) "-I$(PERL_ARCHLIB)" "-I$(PERL_LIB)" -e 'use AutoSplit;autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1) ;'


# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:

SHELL = /bin/sh
CHMOD = chmod
CP = cp
LD = gcc
MV = mv
NOOP = $(SHELL) -c true
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1

# The following is a portable way to say mkdir -p
# To see which directories are created, change the if 0 to if 1
MKPATH = $(PERL) -I$(PERL_ARCHLIB) -I$(PERL_LIB) -MExtUtils::Command -e mkpath

# This helps us to minimize the effect of the .exists files A yet
# better solution would be to have a stable file in the perl
# distribution with a timestamp of zero. But this solution doesn't
# need any changes to the core distribution and works with older perls
EQUALIZE_TIMESTAMP = $(PERL) -I$(PERL_ARCHLIB) -I$(PERL_LIB) -MExtUtils::Command -e eqtime


# --- MakeMaker dist section skipped.

# --- MakeMaker macro section:
TKDIR = ..


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIB="$(LIB)"\
	LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"\
	OPTIMIZE="$(OPTIMIZE)"


# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:

#all ::	config $(INST_PM) subdirs linkext manifypods

all :: pure_all manifypods
	@$(NOOP)

pure_all :: config pm_to_blib subdirs linkext
	@$(NOOP)

subdirs :: $(MYEXTLIB)
	@$(NOOP)

config :: Makefile $(INST_LIBDIR)/.exists
	@$(NOOP)

config :: $(INST_ARCHAUTODIR)/.exists
	@$(NOOP)

config :: $(INST_AUTODIR)/.exists
	@$(NOOP)

$(INST_AUTODIR)/.exists :: /usr/local/lib/perl5/sun4-solaris/5.00404/CORE/perl.h
	@$(MKPATH) $(INST_AUTODIR)
	@$(EQUALIZE_TIMESTAMP) /usr/local/lib/perl5/sun4-solaris/5.00404/CORE/perl.h $(INST_AUTODIR)/.exists

	-@$(CHMOD) 755 $(INST_AUTODIR)

$(INST_LIBDIR)/.exists :: /usr/local/lib/perl5/sun4-solaris/5.00404/CORE/perl.h
	@$(MKPATH) $(INST_LIBDIR)
	@$(EQUALIZE_TIMESTAMP) /usr/local/lib/perl5/sun4-solaris/5.00404/CORE/perl.h $(INST_LIBDIR)/.exists

	-@$(CHMOD) 755 $(INST_LIBDIR)

$(INST_ARCHAUTODIR)/.exists :: /usr/local/lib/perl5/sun4-solaris/5.00404/CORE/perl.h
	@$(MKPATH) $(INST_ARCHAUTODIR)
	@$(EQUALIZE_TIMESTAMP) /usr/local/lib/perl5/sun4-solaris/5.00404/CORE/perl.h $(INST_ARCHAUTODIR)/.exists

	-@$(CHMOD) 755 $(INST_ARCHAUTODIR)

help:
	perldoc ExtUtils::MakeMaker

Version_check:
	@$(PERL) -I$(PERL_ARCHLIB) -I$(PERL_LIB) \
		-MExtUtils::MakeMaker=Version_check \
		-e "Version_check('$(MM_VERSION)')"


# --- MakeMaker linkext section:

linkext :: 
	@$(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make dynamic"
#dynamic :: Makefile $(INST_DYNAMIC) $(INST_BOOT) $(INST_PM)
dynamic :: Makefile $(INST_DYNAMIC) $(INST_BOOT)
	@$(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
#static :: Makefile $(INST_STATIC) $(INST_PM)
static :: Makefile $(INST_STATIC)
	@$(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

manifypods :
	@$(NOOP)


# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean ::
	-rm -rf *.htm index.html *.bak ./blib $(MAKE_APERL_FILE) $(INST_ARCHAUTODIR)/extralibs.all perlmain.c mon.out core so_locations pm_to_blib *~ */*~ */*/*~ *$(OBJ_EXT) *$(LIB_EXT) perl.exe $(BOOTSTRAP) $(BASEEXT).bso $(BASEEXT).def $(BASEEXT).exp
	-mv Makefile Makefile.old $(DEV_NULL)


# --- MakeMaker realclean section:

# Delete temporary files (via clean) and also delete installed files
realclean purge ::  clean
	rm -rf $(INST_AUTODIR) $(INST_ARCHAUTODIR)
	rm -f 
	rm -rf Makefile Makefile.old


# --- MakeMaker dist_basics section skipped.

# --- MakeMaker dist_core section skipped.

# --- MakeMaker dist_dir section skipped.

# --- MakeMaker dist_test section skipped.

# --- MakeMaker dist_ci section skipped.

# --- MakeMaker install section skipped.

# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE:
	@$(NOOP)


# --- MakeMaker perldepend section:
# Auto generated from GCC's .d files


# --- MakeMaker makefile section:

# We take a very conservative approach here, but it\'s worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
Makefile : Makefile.PL $(CONFIGDEP) /home/perl5/NI-S/Tk8/Tk/Config.pm /home/perl5/NI-S/Tk8/Tk/MMutil.pm
	@echo "Makefile out-of-date with respect to $?"
	@echo "Cleaning current config before rebuilding Makefile..."
	-@$(MV) Makefile Makefile.old
	-$(MAKE) -f Makefile.old clean $(DEV_NULL) || $(NOOP)
	$(PERL) "-I$(PERL_ARCHLIB)" "-I$(PERL_LIB)" Makefile.PL 
	@echo "==> Your Makefile has been rebuilt. <=="
	@echo "==> Please rerun the make command.  <=="
	false

# To change behavior to :: would be nice, but would break Tk b9.02
# so you find such a warning below the dist target.
#Makefile :: $(VERSION_FROM)
#	@echo "Warning: Makefile possibly out of date with $(VERSION_FROM)"


# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = ../tkperl$(EXE_EXT)
FULLPERL      = /usr/local/bin/perl


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = 
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE)
	@echo 'No tests defined for $(NAME) extension.'

test_dynamic :: pure_all

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERL) $(TESTDB_SW) -I$(INST_ARCHLIB) -I$(INST_LIB) -I$(PERL_ARCHLIB) -I$(PERL_LIB) $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker pm_to_blib section:

pm_to_blib: $(TO_INST_PM)
	@$(PERL) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)" \
	"-I$(PERL_ARCHLIB)" "-I$(PERL_LIB)" -MExtUtils::Install \
        -e "pm_to_blib({qw{$(PM_TO_BLIB)}},'$(INST_LIB)/auto')"
	@$(TOUCH) $@


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:
MANFILES = \
	mann/DItem.n \
	mann/Grid.n \
	mann/HList.n \
	mann/InpOnly.n \
	mann/Mwm.n \
	mann/TList.n \
	mann/after.n \
	mann/appname.n \
	mann/bell.n \
	mann/bind.n \
	mann/bindtags.n \
	mann/bitmap.n \
	mann/button.n \
	mann/callbacks.n \
	mann/canvas.n \
	mann/checkbut.n \
	mann/clipboard.n \
	mann/composite.n \
	mann/configspec.n \
	mann/configure.n \
	mann/destroy.n \
	mann/entry.n \
	mann/exit.n \
	mann/fileevent.n \
	mann/focus.n \
	mann/focusNext.n \
	mann/form.n \
	mann/frame.n \
	mann/grab.n \
	mann/grid.n \
	mann/image.n \
	mann/label.n \
	mann/listbox.n \
	mann/lower.n \
	mann/menu.n \
	mann/menubutton.n \
	mann/message.n \
	mann/ondestroy.n \
	mann/option.n \
	mann/options.n \
	mann/overview.n \
	mann/pack.n \
	mann/palette.n \
	mann/photo.n \
	mann/place.n \
	mann/radiobut.n \
	mann/raise.n \
	mann/scale.n \
	mann/scrollbar.n \
	mann/selection.n \
	mann/send.n \
	mann/text.n \
	mann/tixWm.n \
	mann/tkerror.n \
	mann/tkwait.n \
	mann/toplevel.n \
	mann/update.n \
	mann/winfo.n \
	mann/wm.n \
	man2/3DBorder.2 \
	man2/BackgdErr.2 \
	man2/BindTable.2 \
	man2/CanvPsY.2 \
	man2/CanvTkwin.2 \
	man2/CanvTxtInf.2 \
	man2/Clipbrd.2 \
	man2/ClrSelect.2 \
	man2/CnfgWidg.2 \
	man2/CnfgWind.2 \
	man2/CoordToWin.2 \
	man2/CrtErrHdlr.2 \
	man2/CrtGenHdlr.2 \
	man2/CrtImgTyp.2 \
	man2/CrtItemTyp.2 \
	man2/CrtMainWin.2 \
	man2/CrtPhImgFm.2 \
	man2/CrtSelHdlr.2 \
	man2/DeleteImg.2 \
	man2/DoOneEvent.2 \
	man2/DoWhenIdle.2 \
	man2/DrawFocHlt.2 \
	man2/EventHndlr.2 \
	man2/EventInit.2 \
	man2/FileHndlr.2 \
	man2/FindPhoto.2 \
	man2/FreeXId.2 \
	man2/GeomReq.2 \
	man2/GetAnchor.2 \
	man2/GetBitmap.2 \
	man2/GetCapStyl.2 \
	man2/GetClrmap.2 \
	man2/GetColor.2 \
	man2/GetCursor.2 \
	man2/GetFontStr.2 \
	man2/GetGC.2 \
	man2/GetImage.2 \
	man2/GetJoinStl.2 \
	man2/GetJustify.2 \
	man2/GetOption.2 \
	man2/GetPixels.2 \
	man2/GetPixmap.2 \
	man2/GetRelief.2 \
	man2/GetRootCrd.2 \
	man2/GetScroll.2 \
	man2/GetSelect.2 \
	man2/GetUid.2 \
	man2/GetVRoot.2 \
	man2/GetVisual.2 \
	man2/IdToWindow.2 \
	man2/ImgChanged.2 \
	man2/InternAtom.2 \
	man2/MainWin.2 \
	man2/MaintGeom.2 \
	man2/ManageGeom.2 \
	man2/MapWindow.2 \
	man2/MoveToplev.2 \
	man2/Name.2 \
	man2/NameOfImg.2 \
	man2/OwnSelect.2 \
	man2/Preserve.2 \
	man2/Restack.2 \
	man2/RestrictEv.2 \
	man2/SetAppName.2 \
	man2/SetClass.2 \
	man2/SetGrid.2 \
	man2/SetVisual.2 \
	man2/Sleep.2 \
	man2/StrictMot.2 \
	man2/TimerHndlr.2 \
	man2/Tk_Main.2 \
	man2/WindowId.2

html : config index.html

index.html : man2html $(MANFILES) $(INST_MAN1DIR) $(INST_MAN3DIR) MANFILES
	@echo "Making HTML"
	@$(PERL) man2html -tk -man1 $(INST_MAN1DIR) \
	         -man3 $(INST_MAN3DIR) -q -files MANFILES
podify: 
	$(PERL) tkman2pod $(MANFILES)
	touch podify

subpodify: tkman2pod $(MANFILES)
	$(PERL) tkman2pod -s $(MANFILES)
	touch subpodify

tk.ipf: subpodify
	pod2ipf --nofaqs --debug --by-dirs "--title=Tk/Perl book" \
		"--section-name=Perl/Tk Constructs" --dir=constructs \
		"--section-name=Tk Generic Methods" --dir=generic \
		"--section-name=Tk User Interaction" --dir=interaction \
		"--section-name=Partially Converted Methods" --dir=unfinished \
		"--section-name=Tix Extensions" --dir=tix \
		"--section-name=Tk Geometry Management" --dir=geometry \
		"--section-name=Tk Selection Handling" --dir=selection \
		"--section-name=Tk Image Classes" --dir=image_classes \
		"--section-name=Tk Library Procedures" --dir=library \
		"--section-name=Tk Modules" --dir=../blib/lib \
			--about > tk.ipf

tk.inf: tk.ipf
	ipfc /inf tk.ipf


# End.
