#!/usr/local/bin/perl -w
my @files = `ls man2/*.2`;
foreach my $src (@files)
 {                      
  chomp($src);
  $src = "//depot/Tk8/doc/$src";
  $dst = $src;
  $src =~ s/Tk8/Tk/;
  $dst =~ s/\.2$/.3/;
  $dst =~ s/man2/man3/;
  print "\t$src $dst\n";
 }
