#!/usr/local/bin/new/perl -w
use strict;
use File::Find;

use ExtUtils::Manifest "/mani/";

my $files = maniread();

find(\&wanted,'.');

sub wanted
{
 return unless -f $_;
 return if -w $_;
 return unless /\.[3n]$/;
 my $name = $File::Find::name;
 $name =~ s#^\./##;
 if (exists $files->{$name})
  {

  }
 else
  {
   warn "Don't need $name\n";
   system('p4','delete',$name);
  }
}


