=head1 NAME

B<Tk> - An Object Oriented Tk4.0 Extension for perl5

=head1 SYNOPSIS

    use Tk;
    $main = MainWindow->new();
    $widget = $main->Widget(...);
    $widget->pack(...);
    MainLoop;

=head1 DESCRIPTION

L<Composite Widgets>

=head2 Design Philosophy

In writing the perl Tk extension, the goals were to provide a complete
interface to the latest version of John Ousterhout's Tk, while providing 
an Object Oriented interface to perl code.

=head1 CONTENTS

The package is composed of three loosely connected parts:

=over 4

=item F<pTk> - Converted Tk source

The F<pTk> sub-directory is a copy of the C code of S<Tk4.0>, modified
to allow use by languages other than the original TCL.
(The S<pTk> can be read as 'perl' Tk or 'portable' Tk, depending on
your sensibilities.) 

=item C<Tk> to Perl "Glue"

The top level directory provides F<Tk.xs>, F<nIO.xs> and F<tkGlue.c>
which provide the perl-callable interfaces to pTk

=item Perl code for "Widget" Classes

The F<Tk/Tk> sub-directory contains the various perl modules that comprise
the "Classes" that are visible to Tk applications.

The "major" widgets such as C<Tk::Text> are actually in separate directories
at the top level (e.g. F<Text/*> for C<Tk::Text>) and are dynamically
loaded as needed on platforms which support perl5's C<DynaLoader>.

=back 

=head1 CLASS HIERARCHY

=head2 C<package Tk;> - the "base class".

All the "command names" documented in Tcl/Tk are made to look like perl
sub's and reside in the Tk package. Their names are all lower case.
Typically there are very few commands at this level which are called 
directly by applications.

=head2 C<package Tk::Widget;> - the "Widget class".

There are no actual objects of the C<Tk::Widget> class; however all 
the various Tk window "widgets" inherit from it, and it in turn
inherits all the core Tk functions from Tk.

C<Tk::Widget> provides various functions and interfaces which are 
common to all Widgets.

A widget is represented to perl as a blessed reference to a hash. There are some
members of the hash which are private to Tk and its tkGlue code.  Keys
starting with C<'.'> and of the form  C</_[A-Z][A-Za-z_]+_/>
(i.e. starting and ending in _ and with  first char after _ being upper case) should be
considered reserved to B<Tk>.

=head2 C<Tk::Button>, C<Tk::Entry>, C<Tk::Text> ...

There is one class for each of the S<"Tk"> widget item types.
Some of them like C<Tk::Frame> do very little indeed, and really 
only exist so that they can be derived from or so that focus or menu
traversal can discover the "kind" of window being processed.

Other classes, C<Tk::Text> for example, provide a lot of methods 
used with Tk's "bind" to provide a rich keyboard/mouse interface
to the widgets' data.

These widget classes also include conversions of the Tcl code for 
event bindings, keyboard focus traversal, menu bars, and menu keyboard
traversal. All the Tcl functions have been converted, but the names have
changed (systematically) and they have been split up between the various
classes in what I hope is an appropriate manner.
Name changes are normally: dropping initial tk_ as the Tk-ness is implicit
in the C<Tk::> prefix, and similarly dropping say Menu from the name if it
has been moved the Tk::Menu class.
Thus 'proc tkMenuNextEntry' becomes 'sub NextEntry' in the Tk::Menu package. 

=head2 C<Tk::Image>

This does for Tk4.0's "images" what C<Tk::Widget> does for widgets.
Images are new to Tk4.0 and the class structure is not mature either.

There are three sub-classes C<Tk::Bitmap>, C<Tk::Pixmap> and C<Tk::Photo>.

It is expected that C<Tk::Image> hierarchy will evolve during the "beta"
phase of Tk to allow dynamic or aud-loaded image types or photo formats.

=head2 Composite Widgets

C<Tk::ScrolledListbox> and C<Tk::Dialog> are examples of 
composite widgets classes built from the basic C<Tk> ones. 

Composite widgets are implemented via multiple inheritance.
There are two base classes C<Tk::Composite::Frame> and
C<Tk::Composite::Toplevel>. 

A Composite widget is typically defined as derived
from C<Tk::Composite::Frame> (e.g. C<Tk::ScrolledListbox>) if it 
is a C<Tk::Frame> with sub-widgets, or C<Tk::Composite::Toplevel> 
(e.g. C<Tk::Dialog>) if it is a C<Tk::Toplevel> with subwidgets.

I expect the style and number of composite and derived classes to evolve when
B<Tk> reaches a larger number of people during the "beta" phase.


