#!/bin/sh 
old=/tmp/xpm-3.4h/lib
new=/tmp/xpm-3.4i/lib
files=`(cd .; ls *.[ch])`
rm -f Fixup 
for f in $files
 do 
  if [ -f $old/$f ]
   then 
    if merge $f $old/$f $new/$f 
     then echo "    $f is okay"
     else 
      echo ">>> $f needs fixing"
      echo $f >> Fixup 
    fi 
  fi 
 done
#!/bin/sh 
old=/tmp/xpm-3.4h/lib
new=/tmp/xpm-3.4i/lib
files=`(cd .; ls *.[ch])`
rm -f Fixup 
for f in $files
 do 
  if [ -f $old/$f ]
   then 
    if merge $f $old/$f $new/$f 
     then echo "    $f is okay"
     else 
      echo ">>> $f needs fixing"
      echo $f >> Fixup 
    fi 
  fi 
 done
