#!/bin/sh
while [ $# -gt 0 ]
 do 
  if [ -f mTk/$1 ]
   then true
   else
    if [ -f Tk/$1 ]
     then 
      cp Tk/$1 mTk/$1
      chmod +w mTk/$1
     else
      echo "No Tk/$1"
    fi 
  fi
  shift
 done
