#ifndef _TIX_VM
#define _TIX_VM
#include "tix_f.h"
#define specTable (*TixVptr->V_specTable)
#define Tix_AppInit (*TixVptr->V_Tix_AppInit)
#define Tix_CallMethod (*TixVptr->V_Tix_CallMethod)
#define Tix_ChangeOneOption (*TixVptr->V_Tix_ChangeOneOption)
#define Tix_CreateCommands (*TixVptr->V_Tix_CreateCommands)
#define Tix_ExistMethod (*TixVptr->V_Tix_ExistMethod)
#define Tix_Exit (*TixVptr->V_Tix_Exit)
#define Tix_FindConfigSpecByName (*TixVptr->V_Tix_FindConfigSpecByName)
#define Tix_FindMethod (*TixVptr->V_Tix_FindMethod)
#define Tix_FindPublicMethod (*TixVptr->V_Tix_FindPublicMethod)
#define Tix_GetClassByName (*TixVptr->V_Tix_GetClassByName)
#define Tix_GetConfigSpecFullName (*TixVptr->V_Tix_GetConfigSpecFullName)
#define Tix_GetContext (*TixVptr->V_Tix_GetContext)
#define Tix_GetMethodFullName (*TixVptr->V_Tix_GetMethodFullName)
#define Tix_GetPublicMethods (*TixVptr->V_Tix_GetPublicMethods)
#define Tix_GetScrollFractions (*TixVptr->V_Tix_GetScrollFractions)
#define Tix_GetWidgetOption (*TixVptr->V_Tix_GetWidgetOption)
#define Tix_HandleSubCmds (*TixVptr->V_Tix_HandleSubCmds)
#define Tix_Init (*TixVptr->V_Tix_Init)
#define Tix_LinkListAppend (*TixVptr->V_Tix_LinkListAppend)
#define Tix_LinkListDelete (*TixVptr->V_Tix_LinkListDelete)
#define Tix_LinkListDeleteRange (*TixVptr->V_Tix_LinkListDeleteRange)
#define Tix_LinkListFind (*TixVptr->V_Tix_LinkListFind)
#define Tix_LinkListInit (*TixVptr->V_Tix_LinkListInit)
#define Tix_LinkListInsert (*TixVptr->V_Tix_LinkListInsert)
#define Tix_LinkListIteratorInit (*TixVptr->V_Tix_LinkListIteratorInit)
#define Tix_LinkListNext (*TixVptr->V_Tix_LinkListNext)
#define Tix_LinkListStart (*TixVptr->V_Tix_LinkListStart)
#define Tix_LoadTclLibrary (*TixVptr->V_Tix_LoadTclLibrary)
#define Tix_MainLoop (*TixVptr->V_Tix_MainLoop)
#define Tix_OpenStdin (*TixVptr->V_Tix_OpenStdin)
#define Tix_RestoreContext (*TixVptr->V_Tix_RestoreContext)
#define Tix_SaveContext (*TixVptr->V_Tix_SaveContext)
#define Tix_SetArgv (*TixVptr->V_Tix_SetArgv)
#define Tix_SuperClass (*TixVptr->V_Tix_SuperClass)
#define Tix_SysInit (*TixVptr->V_Tix_SysInit)
#define Tix_UnknownPublicMethodError (*TixVptr->V_Tix_UnknownPublicMethodError)
#define Tix_ValueMissingError (*TixVptr->V_Tix_ValueMissingError)
#define Tix_WishInit (*TixVptr->V_Tix_WishInit)
#define Tk_Draw3DArc (*TixVptr->V_Tk_Draw3DArc)
#endif /* _TIX_VM */
