#ifndef _TIXINT_VM
#define _TIXINT_VM
#include "tixInt_f.h"
#define TixDItemGetAnchor (*TixintVptr->V_TixDItemGetAnchor)
#define TixDItemStyleChanged (*TixintVptr->V_TixDItemStyleChanged)
#define TixDItemStyleFree (*TixintVptr->V_TixDItemStyleFree)
#define TixGetColorDItemGC (*TixintVptr->V_TixGetColorDItemGC)
#define TixGetDefaultDItemStyle (*TixintVptr->V_TixGetDefaultDItemStyle)
#define Tix_AddDItemType (*TixintVptr->V_Tix_AddDItemType)
#define Tix_ConfigureInfo2 (*TixintVptr->V_Tix_ConfigureInfo2)
#define Tix_DItemCalculateSize (*TixintVptr->V_Tix_DItemCalculateSize)
#define Tix_DItemConfigure (*TixintVptr->V_Tix_DItemConfigure)
#define Tix_DItemCreate (*TixintVptr->V_Tix_DItemCreate)
#define Tix_DItemDisplay (*TixintVptr->V_Tix_DItemDisplay)
#define Tix_DItemFree (*TixintVptr->V_Tix_DItemFree)
#define Tix_GetDItemType (*TixintVptr->V_Tix_GetDItemType)
#define Tix_Init_Internal (*TixintVptr->V_Tix_Init_Internal)
#define Tix_MultiConfigureInfo (*TixintVptr->V_Tix_MultiConfigureInfo)
#define Tix_SetDefaultStyleTemplate (*TixintVptr->V_Tix_SetDefaultStyleTemplate)
#define Tix_SetWindowItemSerial (*TixintVptr->V_Tix_SetWindowItemSerial)
#define Tix_SplitConfig (*TixintVptr->V_Tix_SplitConfig)
#define Tix_UnmapInvisibleWindowItems (*TixintVptr->V_Tix_UnmapInvisibleWindowItems)
#define Tix_WidgetConfigure2 (*TixintVptr->V_Tix_WidgetConfigure2)
#define Tix_WindowItemListRemove (*TixintVptr->V_Tix_WindowItemListRemove)
#endif /* _TIXINT_VM */
