#!perl
use Cwd;
use Config;
use File::Copy;
warn __FILE__." in ".getcwd()."\n";
if ($^O eq 'MSWin32')
 {
  my $file;
  chmod(0666,'Makefile');
  if ($Config{'cc'} =~ /gcc/)
   {
    $file = "nt/Makefile.gcc";
   }
  else
   {
    $file = 'nt/makefile.nt';
    warn "Assuming ".$Config{'cc'}." is visual C of some kind\n";
   }
  copy($file,"Makefile")
   || die "Cannot copy $file to Makefile:$!";
 }
else
 {
  system(sh => "./configure");
 }
1;
