#!/usr/local/bin/perl

BEGIN { unshift(@INC,'../blib') }

require Tk::HTMLtest;

my $html = `cat ../doc/canvas.ht`;

my $obj = Tk::HTMLtest->new();

my $t = time();

$obj->html($html);

print time()-$t," seconds\n";


