.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH LISTBOX 1 "perl 5.005, patch 53" "31/Jul/98" "User Contributed Perl Documentation"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
Tk::Listbox \- Create and manipulate Listbox widgets
.SH "SYNOPSIS"
\fI$listbox\fR = \fI$parent\fR\->\fBListbox\fR(?\fIoptions\fR?);
.SH "STANDARD OPTIONS"
\fB\-background\fR	\fB\-foreground\fR	\fB\-relief\fR	\fB\-takefocus\fR
\fB\-borderwidth\fR	\fB\-height\fR	\fB\-selectbackground\fR	\fB\-width\fR
\fB\-cursor\fR	\fB\-highlightbackground\fR	\fB\-selectborderwidth\fR	\fB\-xscrollcommand\fR
\fB\-exportselection\fR	\fB\-highlightcolor\fR	\fB\-selectforeground\fR	\fB\-yscrollcommand\fR
\fB\-font\fR	\fB\-highlightthickness\fR	\fB\-setgrid\fR
.PP
See the \fITk::options\fR manpage for details of the standard options.
.SH "WIDGET\-SPECIFIC OPTIONS"
.Ip "Name:	\fBheight\fR" 4
.Ip "Class:	\fBHeight\fR" 4
.Ip "Switch:	\fB\-height\fR" 4
Specifies the desired height for the window, in lines.
If zero or less, then the desired height for the window is made just
large enough to hold all the elements in the listbox.
.Ip "Name:	\fBselectMode\fR" 4
.Ip "Class:	\fBSelectMode\fR" 4
.Ip "Switch:	\fB\-selectmode\fR" 4
Specifies one of several styles for manipulating the selection.
The value of the option may be arbitrary, but the default bindings
expect it to be either \fBsingle\fR, \fBbrowse\fR, \fBmultiple\fR,
or \fBextended\fR;  the default value is \fBbrowse\fR.
.Ip "Name:	\fBwidth\fR" 4
.Ip "Class:	\fBWidth\fR" 4
.Ip "Switch:	\fB\-width\fR" 4
Specifies the desired width for the window in characters.
If the font doesn't have a uniform width then the width of the
character ``0'\*(R' is used in translating from character units to
screen units.
If zero or less, then the desired width for the window is made just
large enough to hold all the elements in the listbox.
.SH "DESCRIPTION"
The \fBListbox\fR method creates a new window (given by the
\f(CW$widget\fR argument) and makes it into a listbox widget.
Additional
options, described above, may be specified on the command line
or in the option database
to configure aspects of the listbox such as its colors, font,
text, and relief.  The \fBlistbox\fR command returns its
\f(CW$widget\fR argument.  At the time this command is invoked,
there must not exist a window named \f(CW$widget\fR, but
\f(CW$widget\fR's parent must exist.
.PP
A listbox is a widget that displays a list of strings, one per line.
When first created, a new listbox has no elements.
Elements may be added or deleted using methods described
below.  In addition, one or more elements may be selected as described
below.
If a listbox is exporting its selection (see \fBexportSelection\fR
option), then it will observe the standard X11 protocols
for handling the selection.
Listbox selections are available as type \fBSTRING\fR;
the value of the selection will be the text of the selected elements, with
newlines separating the elements.
.PP
It is not necessary for all the elements to be
displayed in the listbox window at once;  commands described below
may be used to change the view in the window.  Listboxes allow
scrolling in both directions using the standard \fBxScrollCommand\fR
and \fByScrollCommand\fR options.
They also support scanning, as described below.
.SH "INDICES"
Many of the methods for listboxes take one or more indices
as arguments.
An index specifies a particular element of the listbox, in any of
the following ways:
.Ip "\fInumber\fR" 4
Specifies the element as a numerical index, where 0 corresponds
to the first element in the listbox.
.Ip "\fBactive\fR" 4
Indicates the element that has the location cursor.  This element
will be displayed with an underline when the listbox has the
keyboard focus, and it is specified with the \fBactivate\fR
method.
.Ip "\fBanchor\fR" 4
Indicates the anchor point for the selection, which is set with the
\fBselection anchor\fR method.
.Ip "\fBend\fR" 4
Indicates the end of the listbox.
For most commands this refers to the last element in the listbox,
but for a few commands such as \fBindex\fR and \fBinsert\fR
it refers to the element just after the last one.
.Ip "\fB@\fR\fIx\fR\fB,\fR\fIy\fR" 4
Indicates the element that covers the point in the listbox window
specified by \fIx\fR and \fIy\fR (in pixel coordinates).  If no
element covers that point, then the closest element to that
point is used.
.PP
In the method descriptions below, arguments named \fIindex\fR,
\fIfirst\fR, and \fIlast\fR always contain text indices in one of
the above forms.
.SH "WIDGET METHODS"
The \fBListbox\fR method creates a widget object.
This object supports the \fBconfigure\fR and \fBcget\fR methods
described in the \fITk::options\fR manpage which can be used to enquire and
modify the options described above.
The widget also inherits all the methods provided by the generic
Tk::Widget class.
.PP
The following additional methods are available for listbox widgets:
.Ip "\fI$listbox\fR\->\fBactivate\fR(\fIindex\fR)" 4
Sets the active element to the one indicated by \fIindex\fR.
If \fIindex\fR is outside the range of elements in the listbox
then the closest element is activated.
The active element is drawn with an underline when the widget
has the input focus, and its index may be retrieved with the
index \fBactive\fR.
.Ip "\fI$listbox\fR\->\fBbbox\fR(\fIindex\fR)" 4
Returns a list of four numbers describing the bounding box of
the text in the element given by \fIindex\fR.
The first two elements of the list give the x and y coordinates
of the upper-left corner of the screen area covered by the text
(specified in pixels relative to the widget) and the last two
elements give the width and height of the area, in pixels.
If no part of the element given by \fIindex\fR is visible on the
screen,
or if \fIindex\fR refers to a non-existent element,
then the result is an empty string;  if the element is
partially visible, the result gives the full area of the element,
including any parts that are not visible.
.Ip "\fI$listbox\fR\->\fBcurselection\fR" 4
Returns a list containing the numerical indices of
all of the elements in the listbox that are currently selected.
If there are no elements selected in the listbox then an empty
string is returned.
.Ip "\fI$listbox\fR\->\fBdelete\fR(\fIfirst, \fR?\fIlast\fR?)" 4
Deletes one or more elements of the listbox.  \fIFirst\fR and \fIlast\fR
are indices specifying the first and last elements in the range
to delete.  If \fIlast\fR isn't specified it defaults to
\fIfirst\fR, i.e. a single element is deleted.
.Ip "\fI$listbox\fR\->\fBget\fR(\fIfirst, \fR?\fIlast\fR?)" 4
If \fIlast\fR is omitted, returns the contents of the listbox
element indicated by \fIfirst\fR,
or an empty string if \fIfirst\fR refers to a non-existent element.
If \fIlast\fR is specified, the command returns a list whose elements
are all of the listbox elements between \fIfirst\fR and \fIlast\fR,
inclusive.
Both \fIfirst\fR and \fIlast\fR may have any of the standard
forms for indices.
.Ip "\fI$listbox\fR\->\fBindex\fR(\fIindex\fR)" 4
Returns the integer index value that corresponds to \fIindex\fR.
If \fIindex\fR is \fBend\fR the return value is a count of the number
of elements in the listbox (not the index of the last element).
.Ip "\fI$listbox\fR\->\fBinsert\fR(\fIindex, \fR?\fIelement, element, ...\fR?)" 4
Inserts zero or more new elements in the list just before the
element given by \fIindex\fR.  If \fIindex\fR is specified as
\fBend\fR then the new elements are added to the end of the
list.  Returns an empty string.
.Ip "\fI$listbox\fR\->\fBnearest\fR(\fIy\fR)" 4
Given a y-coordinate within the listbox window, this command returns
the index of the (visible) listbox element nearest to that y-coordinate.
.Ip "\fI$listbox\fR\->\fBscan\fR(\fIoption, args\fR)" 4
This command is used to implement scanning on listboxes.  It has
two forms, depending on \fIoption\fR:
.Ip "\fI$listbox\fR\->\fBscanMark\fR(\fIx, y\fR)" 12
Records \fIx\fR and \fIy\fR and the current view in the listbox
window;  used in conjunction with later \fBscan dragto\fR commands.
Typically this command is associated with a mouse button press in
the widget.  It returns an empty string.
.Ip "\fI$listbox\fR\->\fBscanDragto\fR(\fIx, y\fR.)" 12
This command computes the difference between its \fIx\fR and \fIy\fR
arguments and the \fIx\fR and \fIy\fR arguments to the last
\fBscan mark\fR command for the widget.
It then adjusts the view by 10 times the
difference in coordinates.  This command is typically associated
with mouse motion events in the widget, to produce the effect of
dragging the list at high speed through the window.  The return
value is an empty string.
.Ip "\fI$listbox\fR\->\fBsee\fR(\fIindex\fR)" 4
Adjust the view in the listbox so that the element given by \fIindex\fR
is visible.
If the element is already visible then the command has no effect;
if the element is near one edge of the window then the listbox
scrolls to bring the element into view at the edge;  otherwise
the listbox scrolls to center the element.
.Ip "\fI$listbox\fR\->\fBselection\fR(\fIoption, arg\fR)" 4
This command is used to adjust the selection within a listbox.  It
has several forms, depending on \fIoption\fR:
.Ip "\fI$listbox\fR\->\fBselectionAnchor\fR(\fIindex\fR)" 12
Sets the selection anchor to the element given by \fIindex\fR.
If \fIindex\fR refers to a non-existent element, then the closest
element is used.
The selection anchor is the end of the selection that is fixed
while dragging out a selection with the mouse.
The index \fBanchor\fR may be used to refer to the anchor
element.
.Ip "\fI$listbox\fR\->\fBselectionClear\fR(\fIfirst, \fR?\fIlast\fR?)" 12
If any of the elements between \fIfirst\fR and \fIlast\fR
(inclusive) are selected, they are deselected.
The selection state is not changed for elements outside
this range.
.Ip "\fI$listbox\fR\->\fBselectionIncludes\fR(\fIindex\fR)" 12
Returns 1 if the element indicated by \fIindex\fR is currently
selected, 0 if it isn't.
.Ip "\fI$listbox\fR\->\fBselectionSet\fR(\fIfirst, \fR?\fIlast\fR?)" 12
Selects all of the elements in the range between
\fIfirst\fR and \fIlast\fR, inclusive, without affecting
the selection state of elements outside that range.
.Ip "\fI$listbox\fR\->\fBsize\fR" 4
Returns a decimal string indicating the total number of elements
in the listbox.
.Ip "\fI$listbox\fR\->\fBxview\fR(\fIargs\fR)" 4
This command is used to query and change the horizontal position of the
information in the widget's window.  It can take any of the following
forms:
.Ip "\fI$listbox\fR\->\fBxview\fR" 12
Returns a list containing two elements.
Each element is a real fraction between 0 and 1;  together they describe
the horizontal span that is visible in the window.
For example, if the first element is .2 and the second element is .6,
20% of the listbox's text is off-screen to the left, the middle 40% is visible
in the window, and 40% of the text is off-screen to the right.
These are the same values passed to scrollbars via the \fB\-xscrollcommand\fR
option.
.Ip "\fI$listbox\fR\->\fBxview\fR(\fIindex\fR)" 12
Adjusts the view in the window so that the character position given by
\fIindex\fR is displayed at the left edge of the window.
Character positions are defined by the width of the character \fB0\fR.
.Ip "\fI$listbox\fR\->\fBxview\fR(\fBmoveto\fR => \fIfraction\fR)" 12
Adjusts the view in the window so that \fIfraction\fR of the
total width of the listbox text is off-screen to the left.
\fIfraction\fR must be a fraction between 0 and 1.
.Ip "\fI$listbox\fR\->\fBxview\fR(\fBscroll\fR => \fInumber, what\fR)" 12
This command shifts the view in the window left or right according to
\fInumber\fR and \fIwhat\fR.
\fINumber\fR must be an integer.
\fIWhat\fR must be either \fBunits\fR or \fBpages\fR or an abbreviation
of one of these.
If \fIwhat\fR is \fBunits\fR, the view adjusts left or right by
\fInumber\fR character units (the width of the \fB0\fR character)
on the display;  if it is \fBpages\fR then the view adjusts by
\fInumber\fR screenfuls.
If \fInumber\fR is negative then characters farther to the left
become visible;  if it is positive then characters farther to the right
become visible.
.Ip "\fI$listbox\fR\->\fByview\fR(\fI?args\fR?)" 4
This command is used to query and change the vertical position of the
text in the widget's window.
It can take any of the following forms:
.Ip "\fI$listbox\fR\->\fByview\fR" 12
Returns a list containing two elements, both of which are real fractions
between 0 and 1.
The first element gives the position of the listbox element at the
top of the window, relative to the listbox as a whole (0.5 means
it is halfway through the listbox, for example).
The second element gives the position of the listbox element just after
the last one in the window, relative to the listbox as a whole.
These are the same values passed to scrollbars via the \fB\-yscrollcommand\fR
option.
.Ip "\fI$listbox\fR\->\fByview\fR(\fIindex\fR)" 12
Adjusts the view in the window so that the element given by
\fIindex\fR is displayed at the top of the window.
.Ip "\fI$listbox\fR\->\fByview\fR(\fBmoveto\fR => \fIfraction\fR)" 12
Adjusts the view in the window so that the element given by \fIfraction\fR
appears at the top of the window.
\fIFraction\fR is a fraction between 0 and 1;  0 indicates the first
element in the listbox, 0.33 indicates the element one-third the
way through the listbox, and so on.
.Ip "\fI$listbox\fR\->\fByview\fR(\fBscroll\fR => \fInumber, what\fR)" 12
This command adjusts the view in the window up or down according to
\fInumber\fR and \fIwhat\fR.
\fINumber\fR must be an integer.
\fIWhat\fR must be either \fBunits\fR or \fBpages\fR.
If \fIwhat\fR is \fBunits\fR, the view adjusts up or down by
\fInumber\fR lines;  if it is \fBpages\fR then
the view adjusts by \fInumber\fR screenfuls.
If \fInumber\fR is negative then earlier elements
become visible;  if it is positive then later elements
become visible.
.SH "DEFAULT BINDINGS"
Tk automatically creates class bindings for listboxes that give them
Motif-like behavior.  Much of the behavior of a listbox is determined
by its \fBselectMode\fR option, which selects one of four ways
of dealing with the selection.
.PP
If the selection mode is \fBsingle\fR or \fBbrowse\fR, at most one
element can be selected in the listbox at once.
In both modes, clicking button 1 on an element selects
it and deselects any other selected item.
In \fBbrowse\fR mode it is also possible to drag the selection
with button 1.
.PP
If the selection mode is \fBmultiple\fR or \fBextended\fR,
any number of elements may be selected at once, including discontiguous
ranges.  In \fBmultiple\fR mode, clicking button 1 on an element
toggles its selection state without affecting any other elements.
In \fBextended\fR mode, pressing button 1 on an element selects
it, deselects everything else, and sets the anchor to the element
under the mouse;  dragging the mouse with button 1
down extends the selection to include all the elements between
the anchor and the element under the mouse, inclusive.
.PP
Most people will probably want to use \fBbrowse\fR mode for
single selections and \fBextended\fR mode for multiple selections;
the other modes appear to be useful only in special situations.
.PP
In addition to the above behavior, the following additional behavior
is defined by the default bindings:
.Ip "[1]" 4
In \fBextended\fR mode, the selected range can be adjusted by pressing
button 1 with the Shift key down:  this modifies the selection to
consist of the elements between the anchor and the element under
the mouse, inclusive.
The un-anchored end of this new selection can also be dragged with
the button down.
.Ip "[2]" 4
In \fBextended\fR mode, pressing button 1 with the Control key down
starts a toggle operation: the anchor is set to the element under
the mouse, and its selection state is reversed.  The selection state
of other elements isn't changed.
If the mouse is dragged with button 1 down, then the selection state
of all elements between the anchor and the element under the mouse
is set to match that of the anchor element;  the selection state of
all other elements remains what it was before the toggle operation
began.
.Ip "[3]" 4
If the mouse leaves the listbox window with button 1 down, the window
scrolls away from the mouse, making information visible that used
to be off-screen on the side of the mouse.
The scrolling continues until the mouse re-enters the window, the
button is released, or the end of the listbox is reached.
.Ip "[4]" 4
Mouse button 2 may be used for scanning.
If it is pressed and dragged over the listbox, the contents of
the listbox drag at high speed in the direction the mouse moves.
.Ip "[5]" 4
If the Up or Down key is pressed, the location cursor (active
element) moves up or down one element.
If the selection mode is \fBbrowse\fR or \fBextended\fR then the
new active element is also selected and all other elements are
deselected.
In \fBextended\fR mode the new active element becomes the
selection anchor.
.Ip "[6]" 4
In \fBextended\fR mode, Shift-Up and Shift-Down move the location
cursor (active element) up or down one element and also extend
the selection to that element in a fashion similar to dragging
with mouse button 1.
.Ip "[7]" 4
The Left and Right keys scroll the listbox view left and right
by the width of the character \fB0\fR.
Control-Left and Control-Right scroll the listbox view left and
right by the width of the window.
Control-Prior and Control-Next also scroll left and right by
the width of the window.
.Ip "[8]" 4
The Prior and Next keys scroll the listbox view up and down
by one page (the height of the window).
.Ip "[9]" 4
The Home and End keys scroll the listbox horizontally to
the left and right edges, respectively.
.Ip "[10]" 4
Control-Home sets the location cursor to the the first element in
the listbox, selects that element, and deselects everything else
in the listbox.
.Ip "[11]" 4
Control-End sets the location cursor to the the last element in
the listbox, selects that element, and deselects everything else
in the listbox.
.Ip "[12]" 4
In \fBextended\fR mode, Control-Shift-Home extends the selection
to the first element in the listbox and Control-Shift-End extends
the selection to the last element.
.Ip "[13]" 4
In \fBmultiple\fR mode, Control-Shift-Home moves the location cursor
to the first element in the listbox and Control-Shift-End moves
the location cursor to the last element.
.Ip "[14]" 4
The space and Select keys make a selection at the location cursor
(active element) just as if mouse button 1 had been pressed over
this element.
.Ip "[15]" 4
In \fBextended\fR mode, Control-Shift-space and Shift-Select
extend the selection to the active element just as if button 1
had been pressed with the Shift key down.
.Ip "[16]" 4
In \fBextended\fR mode, the Escape key cancels the most recent
selection and restores all the elements in the selected range
to their previous selection state.
.Ip "[17]" 4
Control-slash selects everything in the widget, except in
\fBsingle\fR and \fBbrowse\fR modes, in which case it selects
the active element and deselects everything else.
.Ip "[18]" 4
Control-backslash deselects everything in the widget, except in
\fBbrowse\fR mode where it has no effect.
.Ip "[19]" 4
The F16 key (labelled Copy on many Sun workstations) or Meta-w
copies the selection in the widget to the clipboard, if there is
a selection.
.Sp
The behavior of listboxes can be changed by defining new bindings for
individual widgets or by redefining the class bindings.
.SH "KEYWORDS"
listbox, widget

.rn }` ''
.IX Title "LISTBOX 1"
.IX Name "Tk::Listbox - Create and manipulate Listbox widgets"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "STANDARD OPTIONS"

.IX Header "WIDGET\-SPECIFIC OPTIONS"

.IX Item "Name:	\fBheight\fR"

.IX Item "Class:	\fBHeight\fR"

.IX Item "Switch:	\fB\-height\fR"

.IX Item "Name:	\fBselectMode\fR"

.IX Item "Class:	\fBSelectMode\fR"

.IX Item "Switch:	\fB\-selectmode\fR"

.IX Item "Name:	\fBwidth\fR"

.IX Item "Class:	\fBWidth\fR"

.IX Item "Switch:	\fB\-width\fR"

.IX Header "DESCRIPTION"

.IX Header "INDICES"

.IX Item "\fInumber\fR"

.IX Item "\fBactive\fR"

.IX Item "\fBanchor\fR"

.IX Item "\fBend\fR"

.IX Item "\fB@\fR\fIx\fR\fB,\fR\fIy\fR"

.IX Header "WIDGET METHODS"

.IX Item "\fI$listbox\fR\->\fBactivate\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBbbox\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBcurselection\fR"

.IX Item "\fI$listbox\fR\->\fBdelete\fR(\fIfirst, \fR?\fIlast\fR?)"

.IX Item "\fI$listbox\fR\->\fBget\fR(\fIfirst, \fR?\fIlast\fR?)"

.IX Item "\fI$listbox\fR\->\fBindex\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBinsert\fR(\fIindex, \fR?\fIelement, element, ...\fR?)"

.IX Item "\fI$listbox\fR\->\fBnearest\fR(\fIy\fR)"

.IX Item "\fI$listbox\fR\->\fBscan\fR(\fIoption, args\fR)"

.IX Item "\fI$listbox\fR\->\fBscanMark\fR(\fIx, y\fR)"

.IX Item "\fI$listbox\fR\->\fBscanDragto\fR(\fIx, y\fR.)"

.IX Item "\fI$listbox\fR\->\fBsee\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBselection\fR(\fIoption, arg\fR)"

.IX Item "\fI$listbox\fR\->\fBselectionAnchor\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBselectionClear\fR(\fIfirst, \fR?\fIlast\fR?)"

.IX Item "\fI$listbox\fR\->\fBselectionIncludes\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBselectionSet\fR(\fIfirst, \fR?\fIlast\fR?)"

.IX Item "\fI$listbox\fR\->\fBsize\fR"

.IX Item "\fI$listbox\fR\->\fBxview\fR(\fIargs\fR)"

.IX Item "\fI$listbox\fR\->\fBxview\fR"

.IX Item "\fI$listbox\fR\->\fBxview\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fBxview\fR(\fBmoveto\fR => \fIfraction\fR)"

.IX Item "\fI$listbox\fR\->\fBxview\fR(\fBscroll\fR => \fInumber, what\fR)"

.IX Item "\fI$listbox\fR\->\fByview\fR(\fI?args\fR?)"

.IX Item "\fI$listbox\fR\->\fByview\fR"

.IX Item "\fI$listbox\fR\->\fByview\fR(\fIindex\fR)"

.IX Item "\fI$listbox\fR\->\fByview\fR(\fBmoveto\fR => \fIfraction\fR)"

.IX Item "\fI$listbox\fR\->\fByview\fR(\fBscroll\fR => \fInumber, what\fR)"

.IX Header "DEFAULT BINDINGS"

.IX Item "[1]"

.IX Item "[2]"

.IX Item "[3]"

.IX Item "[4]"

.IX Item "[5]"

.IX Item "[6]"

.IX Item "[7]"

.IX Item "[8]"

.IX Item "[9]"

.IX Item "[10]"

.IX Item "[11]"

.IX Item "[12]"

.IX Item "[13]"

.IX Item "[14]"

.IX Item "[15]"

.IX Item "[16]"

.IX Item "[17]"

.IX Item "[18]"

.IX Item "[19]"

.IX Header "KEYWORDS"

