package Tk::Config;
require Exporter;
use base qw(Exporter);
$VERSION = '800.012';
$inc = '-I../pTk/mTk/xlib -I../../pTk/mTk/xlib -IpTk/mTk/xlib -ImTk/os2_rc';
$define = '-DBASEEXT=\\"$(BASEEXT)\\" -D__PM__ -DINIT_VIA_PERL';
$xlib = '';
$xinc = '';
$gccopt = '';
$win_arch = 'pm';
@EXPORT = qw($VERSION $inc $define $xlib $xinc $gccopt $win_arch);
1;
