package Tk::Config;
require Exporter;
@ISA = qw(Exporter);
$VERSION = '402.003';
$inc = '-I../pTk/mTk/xlib -I../../pTk/mTk/xlib -IpTk/mTk/xlib -ImTk/os2_rc';
$define = '-DBASEEXT=\\"$(BASEEXT)\\" -D__PM__';
$xlib = '';
$xinc = '';
$gccopt = ' -Wall -Wno-comment -Wno-unused -D__USE_FIXED_PROTOTYPES__';
$win_arch = 'pm';
@EXPORT = qw($VERSION $inc $define $xlib $xinc $gccopt $win_arch);
1;
