name: CI for Windows

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Windows + StrawberryPerl ${{ matrix.perl_version }}
    runs-on: windows-latest
    continue-on-error: ${{ matrix.allow_failure }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - perl_version: '5.32'
            allow_failure: false
          - perl_version: 'latest'
            allow_failure: true

    steps:
    - uses: actions/checkout@v4

    - name: Install StrawberryPerl ${{ matrix.perl_version }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl_version }}
        distribution: strawberry

    - name: Configure
      run: perl Makefile.PL

    - name: Build
      run: gmake

    - name: Test
      env:
        HARNESS_TIMER: 1
      run: gmake test
